<?php

include_once('da_wysiwyg.features.inc');

/**
 * Implementation of hook_filter_default_formats_alter().
 */
function da_wysiwyg_filter_default_formats_alter(&$formats) {
  if (isset($formats['Markdown'])) {
    $formats['Markdown']['roles'] = array(
      'anonymous user',
      'authenticated user',
      'authorized user',
      'manager',
      'administrator',
    );
  }
}

/**
* Implementation of hook_strongarm_alter()
*/
function da_wysiwyg_strongarm_alter(&$items) {
  if (isset($items['filter_default_format'])) {
    $items['filter_default_format']->value = '100';
  }
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter().
 */
function da_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['forcePasteAsPlainText'] = TRUE;
  }
}
